# Taps
# (add any custom taps here if needed in future)

# Languages & Runtimes
brew 'deno'
brew 'go'
brew 'lua'
brew 'luarocks'
brew 'nvm'
brew 'pyenv'
brew 'pyenv-virtualenv'

# Development Tools
brew 'awscli'
brew 'buf'
brew 'cmake'
brew 'fzf'
brew 'graphviz'
brew 'kubectl'
brew 'lazygit'
brew 'ncurses'
brew 'neovim'
brew 'pipx'
brew 'ripgrep'
brew 'socat'
brew 'tmux'
brew 'wget'
brew 'gh'

# LSP & Language Servers
brew 'lua-language-server'
brew 'vscode-langservers-extracted'

# Services
brew 'postgresql@14'
brew 'rabbitmq'
brew 'redis'

# Casks
cask 'font-fira-code'
cask 'ngrok'
cask 'ghostty'

