# Development
brew 'nvm'
brew 'lua-language-server'
brew 'kubectl'
brew 'awscli'
brew 'socat'
brew 'vscode-langservers-extracted'

# Apps
brew 'neovim'
brew 'tmux'
brew 'fzf'
brew 'ripgrep'
brew 'cmake'
brew 'deno'
brew 'wget'

# Services
brew 'redis'
brew 'rabbitmq'
