set -g @plugin 'tmux-plugins/tpm'

# Plugins to help with saving and restoring tmux sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Change save dir for tmux-resurrect
set -g @resurrect-dir '~/.tmux/resurrect'

# Save tmux seesion at intervals (15 default)
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Auto start at boot and use iterm as the terminal of choice
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'ghostty'

# Display current status of tmux continuum in tmux status line
set -g status-right 'Continuum status: #{continuum_status}'

# Restore additional programs
set -g @resurrect-processes 'ssh claude'

